### ISSUE TITLE
很棒的一个裁剪工具，但是还可以再完善

### ISSUE THREAD

**Issue by uestchang** [Vesincc/HQImageEditViewController#1]
1.裁剪框的缩放，触摸判断区域太小了，经常没法控制框的缩放
2.裁剪框没有内部做好适应，给出的接口是自定义裁剪框大小而不是比例，其实作为使用者，裁剪框大小一般都不关心，更多关心的是裁剪框比例，裁剪框大小根据屏幕自适应最好了。
3.旋转、缩放过程中也能点  完成  按钮，导致裁剪的结果不符合预期，最好加个全局的  BOOL 去控制，只有动画执行完毕后点击 完成  按钮 才能完成裁剪，否则不触发action
4.提供的自定义接口太少了，如果能完善一下，我觉得有望超过那个2000stars的裁剪库
5.感谢作者开源此裁剪程序 
@Vesincc

**Comment by Vesincc** [comment]
对于第一点和第三点确实是设计的时候没有考虑到，但是对于第二点我和你的理解上有些差异。我倒是觉得给出size反而更加的灵活，现在对于适配来说无非就两种，一个是是固定屏幕比例，一个是固定边距，我给出的size对于这两种适配来说都是很方便的完成的，比例：屏幕宽度*比例计算出size，边距：屏幕宽度-边距，无非就是需要计算出size再传过去，相比于放弃固定边距的适配来说，我觉得给出size反而更加合适。过两天会提交一个版本修复1、3的问题。感谢指正！

**Comment by uestchang** [comment]
@Vesincc 
感谢作者的回复！
我的理解是：
对于调用裁剪程序的程序员来说，传入大小可能还需要经过一步计算得到大小才传进去，这需要程序员自己去考虑不同屏幕大小的适配；如果传比例，程序员可以不用关心内部实现，裁剪程序可以直接内部设定死跟屏幕的一个合适边距，然后按比例调裁剪矩形即可。也就是说，传入比例，对于直接调来说更方便。
当然，如果两个接口都完善，然后开放出来，那就再好不过了。

项目使用过程中，我通过增加判断解决了第3点问题。
现在还遇到些问题，提出来当建议，您可以参考参考：
1.横屏下，先点旋转，动画没结束的情况下马上点击复原功能时，图片显示大小会出现BUG。
2.将mask打开的情况下，竖屏切换为横屏的时候，mask大小没用重新适配横屏
3.缩放调整裁剪框的时候，mask没跟着调整，导致缩放裁剪框过程中缺一部分，缩放完才恢复正常
4.竖屏进入裁剪时，裁剪矩形位置在屏幕中央，切换为横屏后会到屏幕偏上部，然后再切换回竖屏，裁剪矩形的位置就跑到上部去了，虽然不太影响使用，但很违和。
5.进入裁剪程序时，裁剪矩形在中央，然后scrollView的位置是top和裁剪矩形的top重合。这种初始化的预览方式让大多数图片显示都不完整。建议是进入裁剪程序时，图片默认是中心跟裁剪框中心重合，这样效果是让图片尽可能现在在屏幕内，用户才会！ 旋转之后的结果也是建议如此。

**Comment by uestchang** [comment]
对了，还有scrollView的弹力，我直接关了，因为回弹过程中也可以截图，没找到回弹的生命周期开始和结束回调。

**Comment by uestchang** [comment]
横屏模式下，裁剪框直接不能检测缩放

**Comment by uestchang** [comment]
@Vesincc 
兄弟在吗，手动移植裁剪库的时候，到新的项目masonry.h找不到，然后手动再导入masonry框架就出问题了。无论是用cocoaPod导入还是自己手动导入，都会出问题。

**Comment by Vesincc** [comment]
1.横屏模式下的问题
 当时并没有考虑横屏情况，一个裁剪框用户也没必要切换到横屏裁剪吧，我所有的项目都是统一设置只能竖屏，在需要的页面才开放横屏，建议你也这样做
2.A:还有scrollView的弹力，我直接关了，因为回弹过程中也可以截图，没找到回弹的生命周期开始和结束回调。
对于这个其实并没有那么麻烦，UIScrollView提供了一系列的状态，可以通过这些状态判断是否忽略事件响应
3.项目masonry.h找不到
这个应该是你的项目配置有问题

4.裁剪框四个边角触摸区域以及动画过程中 可以完成操作都已经修复

pod暂时还没有更新，先手动导入凑合一下吧
