### ISSUE TITLE
裁剪框希望能够像微信那种，根据手指拖动控制裁剪框的比例和大小，这样灵活一点

### ISSUE THREAD

**Issue by guruifeng** [Vesincc/HQImageEditViewController#7]

**Comment by Vesincc** [comment]
四个角是可以拖动的

**Comment by guruifeng** [comment]
四个角是可以拖，但是是等比缩放的，我觉得，随意拖动比例我觉得就完美了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 韩琪 <notifications@github.com&gt;
发送时间: 2020年1月3日 13:26
收件人: Vesincc/HQImageEditViewController <HQImageEditViewController@noreply.github.com&gt;
抄送: guruifeng <1119202441@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Vesincc/HQImageEditViewController] 裁剪框希望能够像微信那种，根据手指拖动控制裁剪框的比例和大小，这样灵活一点 (#7)
